### ISSUE TITLE
TeamCity 9.x changes not properly displayed in UI

### ISSUE THREAD

**Issue by tupac21354** [AutomatedArchitecture/SirenOfShame#54]
TeamCity 9.x changed the changes element to no longer include the 'count' attribute which as a result is causing the Siren of Shame to not display the user and checkin notes properly. https://confluence.jetbrains.com/display/TCD9/Upgrade+Notes 

I don't have contribute permission but my proposed fix is:

File -> TeamCityService.cs

line 313 -> var getBuildByBuildIdIdUrl = rootUrl + "/httpAuth/app/rest/builds/id:" + buildId + "?fields=$long,changes(count,href)"; ;

line 369 -> var url = rootUrl + "/httpAuth/app/rest/builds/buildType:" + buildDefinitionSetting.Id + "?fields=$long,changes(count,href)";

Thanks,
Chris

**Comment by lprichar** [comment]
Fantastic, thank you @tupac21354 for the detailed analysis and solution!  If you want to be listed as a contributor to the project and bathe in the glory of your addition to this noble and worthy project for the rest of your years you can issue a pull request.  Otherwise I'll incorporate this shortly and steal all that glory for myself :).

**Comment by tupac21354** [comment]
You can have all the glory since I'm still too new to github : )

**Comment by lprichar** [comment]
Thanks again for your contribution @tupac21354. This has been implemented and is now in [2.3.10](http://sirenofshame.com/downloads).  You're even featured in the release notes, which works out quite well since now I can blame you whenever TeamCity fails :).
