### ISSUE TITLE
Custom sounds on build failure

### ISSUE THREAD

**Issue by themilkyninja** [AutomatedArchitecture/SirenOfShame#60]
Hi,

I'm able to upload new sounds, but I can't figure out how to get them to play instead of three default sounds. Is this supported?

**Comment by lprichar** [comment]
It is supported.  Have you seen this: http://blog.sirenofshame.com/2014/04/released-220.html

If that doesn't work, can you check the logs and post any errors you see? http://blog.sirenofshame.com/2012/01/how-to-report-errors.html

**Comment by themilkyninja** [comment]
Yup I followed that, and it works for playing the audio on Windows. Is there any way for it to play the custom sounds on the siren itself?

**Comment by lprichar** [comment]
Oh on the device.  Sorry, I misunderstood.  There is currently no way to upload your own custom audio.  However, have you seen the firmware page: http://www.sirenofshame.com/firmware?  All sirens ship with V2.1, but V1 has some different audio sounds.  

If you have a simple sound that would fit into the 32K of memory on the device I'd be happy to make a firmware package out of it.  They also need to be fairly simple like 8 bitish sounds since the device uses pulse width modulation rather than true analog.  That makes human voices and such sound buzzy.

**Comment by themilkyninja** [comment]
Is it safe to upgrade and downgrade the firmware to test out the different functionality of each? If so, I can play with all of them before trying to do anything more custom.

**Comment by lprichar** [comment]
Yes, it's safe. The version numbers are misleading implying that bigger numbers are newer and better, but they're really just alternatives.

**Comment by themilkyninja** [comment]
Firmware 101 has some good siren sounds, so I think I'm good. In case I want to play with it in the future, is there a way to make my own firmware? Or do I have to go through you? I see it's just XML, but I'm not sure what's encoded in there.

**Comment by lprichar** [comment]
It only pretends to be XML to fool the unwary.  It's actually compiled Atmel AVR machine code.  I'm afraid you'll have to go through us.  We actually have a prototype chip with the ability to upload custom audio that has a great sound quality and plenty of storage space, but we ran into technical difficulties with upload speed.  If you find some good audio clips send them to support at our domain name.

**Comment by themilkyninja** [comment]
Gotcha. Thanks!
